### ISSUE TITLE
Boarbot 'You'll be unbanned at Invalid date!'

### ISSUE THREAD

**Issue by BeAmazedd** [BoarBotDevs/BoarBot#80]
When I /boar market, /boar gift or accept a gift or click on the correct image in a powerup event it says this (might be more I haven't done everything). I am not here to argue against the ban as much as the Invalid Date as there is a reason many bans are temporary in a lot of areas. The 'will be unbanned at invalid date' seems like a bug.
![unknown](https://github.com/BoarBotDevs/BoarBot/assets/154644785/ed59c146-fede-4a4f-8e89-2a40ddf988ac)

**Comment by BlueBM** [comment]
It just means that it's a permanent ban. Could be reworded  to be less confusing.

**Comment by WeslayCodes** [comment]
Thanks for letting me know, I'll bring your ban down to a month-ish. I probably need to be a bit more consistent and not so harsh with it. Alts will remain permanent though.

**Comment by BeAmazedd** [comment]
@WeslayCodes do i need to give my user or anything
