### ISSUE TITLE
Giga Chad Boar Maximum amount sell offer

### ISSUE THREAD

**Issue by BeAmazedd** [BoarBotDevs/BoarBot#94]
You can't sell offer Giga Chad Boar for more than 6k which is substantially lower than the average sell price of all other immaculates and their max sell offer.

**Comment by WeslayCodes** [comment]
Someone sold a gigachad boar for $3k. Price range is 1/2 of prior sale price to 2x prior sale price. Market is being completely reworked in the next version to reduce confusion and generally be easier to use.
