### ISSUE TITLE
Trophy badge doesn't update unless someone runs /boar top

### ISSUE THREAD

**Issue by will-da-pro** [BoarBotDevs/BoarBot#95]
Trophy badges don't update until someone views that leaderboard with /boar top, so it can be inaccurate if someone hasn't run the command for a few days, especially with charm rolling. Would it be possible to make it update whenever someone runs boar collection or would that not work

**Comment by WeslayCodes** [comment]
Having leaderboards update every time somebody does /boar collection would be terrible for performance. The leaderboard only updates when needed, which is when somebody runs /boar top. Things may be different in java edition.
